image: wodby/drupal-php:8.1

pipelines:
  pull-requests:
    '**':
      - step:
          name: 'PHP Code style'
          script:
            - composer --global config repositories.finalist composer https://packeton.finalist.nl/
            - composer config --global --auth http-basic.packeton.finalist.nl $PACKETON_USER $PACKETON_KEY
            - composer install --prefer-dist --no-ansi --no-interaction
            - bin/phpcs --standard=./web/core/phpcs.xml.dist --ignore=vendor web/modules/custom
          caches:
            - composer
