<?php

/**
 * @file
 * Functions to support theming.
 */

/**
 * Load include files which contain additional theming logic.
 */
foreach (glob(\Drupal::service('extension.list.theme')->getPath('tripchoice') . '/includes/*.theme') as $file) {
  include $file;
}


/** * Implements hook_preprocess_node(). */
function tripchoice_preprocess_node(&$variables){
  $variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage();
}
